name: Container Factory
on: 
  push:
    paths:
      - "Python/**"
      - "environment.yml"
      - "apt.txt"
jobs:
  create-and-publish-container:
    runs-on: ubuntu-latest
    steps:
      - name: checkout files in repo
        uses: actions/checkout@master
      - name: run repo2docker an publish image
        uses: jupyterhub/repo2docker-action@master
        with:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}